language: php
php:
- 5.5
sudo: false
services:
- memcached
before_script:
- composer self-update
- composer install --prefer-dist --no-interaction
- phpenv config-add php.travis.ini
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_71c9cafbf2c8_key -iv $encrypted_71c9cafbf2c8_iv
  -in TVAuth-53643d045b1b.json.enc -out TVAuth-53643d045b1b.json -d || true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_71c9cafbf2c8_key
  -iv $encrypted_71c9cafbf2c8_iv -in config.gae.php.enc -out config.php -d || true'
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: TVAuth-53643d045b1b.json
  default: true
  project: tvauth-1133
  on: master
