language: php
php:
- 5.5
- 5.6
sudo: false
services:
- memcached
before_script:
- cp config.template.php config.php
- composer self-update
- composer install --prefer-dist --no-interaction
- phpenv config-add php.travis.ini
