language: php
php:
- 5.4
- 5.5
- nightly
sudo: false
services:
- memcache
before_script:
- cp config.template.php config.php
- composer self-update
- composer install --prefer-dist --no-interaction
before_install:
- openssl aes-256-cbc -K $encrypted_71c9cafbf2c8_key -iv $encrypted_71c9cafbf2c8_iv
  -in TVAuth-1070d2ce7755.json.enc -out TVAuth-1070d2ce7755.json -d
- openssl aes-256-cbc -K $encrypted_71c9cafbf2c8_key -iv $encrypted_71c9cafbf2c8_iv
  -in config.gae.php.enc -out config.php -d
